// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "7a7c4c61-ebc9-49d1-b215-c02b0fefc202";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onHumiChange();
void onSoilhumiChange();
void onTempvarChange();
void onFanoutChange();
void onLightonChange();
void onWateringChange();

float humi;
float soilhumi;
float tempvar;
bool fanout;
bool lighton;
bool watering;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humi, READWRITE, ON_CHANGE, onHumiChange);
  ArduinoCloud.addProperty(soilhumi, READWRITE, ON_CHANGE, onSoilhumiChange);
  ArduinoCloud.addProperty(tempvar, READWRITE, ON_CHANGE, onTempvarChange);
  ArduinoCloud.addProperty(fanout, READWRITE, ON_CHANGE, onFanoutChange);
  ArduinoCloud.addProperty(lighton, READWRITE, ON_CHANGE, onLightonChange);
  ArduinoCloud.addProperty(watering, READWRITE, ON_CHANGE, onWateringChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
